apiVersion: v2
name: ollama
description: A Helm chart for deploying LocalAI
type: application
version: 0.1.0

dependencies:
- name: ollama-helm
  version: "1.36.0"
  repository: "https://otwld.github.io/ollama-helm/"
