grafana:
  additionalDataSources:
    - name: Loki
      type: loki
      isDefault: false
      access: proxy
      url: http://loki:3100
      jsonData:
        timeout: 60
        maxLines: 1000
      version: 1

prometheus:
  istio:
    enabled: true
  volumes:
    - name: config-volume
      configMap:
        name: prometheus
    - name: istio-certs
      secret:
        defaultMode: 420
        optional: true
        secretName: istio.default
  additionalScrapeConfigs:
    - job_name: istiod
      kubernetes_sd_configs:
        - namespaces:
            names:
              - istio-system
          role: endpoints
      relabel_configs:
        - action: keep
          regex: istiod;http-monitoring
          source_labels:
            - __meta_kubernetes_service_name
            - __meta_kubernetes_endpoint_port_name
    - job_name: envoy-stats
      kubernetes_sd_configs:
        - role: pod
      metrics_path: /stats/prometheus
      relabel_configs:
        - action: keep
          regex: .*-envoy-prom
          source_labels:
            - __meta_kubernetes_pod_container_port_name
