redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

server:
  extraArgs:
    - --insecure
  additionalApplications:
    - name: calculation1
      project: default
      source:
        repoURL: 'https://github.com/GustavoGuima86/calculationAPI'
        path: calculation
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: test
      syncPolicy:
        automated: { }