apiVersion: v2
name: keycloak
description: A wrapper Helm chart for Keycloak IAM on EKS
type: application
version: 0.1.0
appVersion: "26.2.4"

dependencies:
  - name: keycloak
    version: "24.4.3"
    repository: "https://codecentric.github.io/helm-charts"
