{
 "title": "VPC CNI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "IPam IP Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(awscni_ip_max)", "legendFormat": "Max IPs" },
    { "expr": "sum(awscni_ip_in_use)", "legendFormat": "IPs in Use" },
    { "expr": "sum(awscni_ip_free)", "legendFormat": "Free IPs" }
   ]
  },
  {
   "title": "IPam Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(awscni_add_ip_req_count[1m]))",
     "legendFormat": "Add IP Requests"
    },
    {
     "expr": "sum(rate(awscni_del_ip_req_count[1m]))",
     "legendFormat": "Delete IP Requests"
    }
   ]
  },
  {
   "title": "IP Addresses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(awscni_total_ip_addresses)", "legendFormat": "Total IPs" },
    {
     "expr": "sum(awscni_assigned_ip_addresses)",
     "legendFormat": "Assigned IPs"
    }
   ]
  }
 ]
}