apiVersion: apps/v1
kind: Deployment
metadata:
  name: holmes
  labels:
    app.kubernetes.io/name: holmes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: holmes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: holmes
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: holmes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: model-list
              mountPath: /etc/holmes/config/model_list.yaml
              subPath: model_list.yaml
          env:
            - name: HOLMES_MODEL_LIST
              value: /etc/holmes/config/model_list.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: model-list
          configMap:
            name: holmes-model-list

