apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: holmes
    app.kubernetes.io/component: serviceaccount
  namespace: {{ .Release.Namespace }}
