apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-ollama-pvc
  namespace: ai-sre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp3-secure"
  resources:
    requests:
      storage: 50Gi