apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-secret-provider
  namespace: observability
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.grafanaAdminPasswordParameterName }}
        objectType: ssmparameter
        jmesPath: "Content"
  secretObjects:
  - secretName: grafana-admin-secret
    type: Opaque
    data:
    - key: GF_SECURITY_ADMIN_PASSWORD
      objectName: {{ .Values.grafanaAdminPasswordParameterName }}
