# ==============================================================================
# Istio Gateway Configuration
# ==============================================================================

acmCertificateArn: "" # From Terraform
rootDomain: "" # From Terraform

gateway:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "false"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.acmCertificateArn }}"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

