{{- if .Values.opencost_role_arn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opencost_sa_name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # Pod Identity association for AWS access
    eks.amazonaws.com/role-arn: {{ .Values.opencost_role_arn }}
{{- end }}
