# Values for the mimir wrapper chart

mimir-distributed:
  serviceAccount:
    create: true
    name: "mimir-sa"
    annotations: {}

  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            bucket_name: "" # Set by ArgoCD
            region: "" # Set by ArgoCD
      validation:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_series_per_metric: 10000
      limits:
        ingestion_rate: 50000

  minio:
    enabled: false

  # Add placeholders for consistency
  clusterName: "" # Set by ArgoCD
  awsRegion: "" # Set by ArgoCD
