apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  BACKEND_SECRET: "{{ .Values.secrets.backendSecret }}"
  GITHUB_TOKEN: "{{ .Values.secrets.githubToken }}"
  # CloudNativePG creates a service named <cluster-name>-rw for read-write connections
  POSTGRES_HOST: "{{ .Values.postgres.host }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
  POSTGRES_DB: "{{ .Values.postgres.database }}"
  AWS_ACCOUNT_ID: "{{ .Values.awsAccountId }}"
  AWS_REGION: "{{ .Values.secrets.awsRegion }}"
  AWS_ROLE_ARN: "{{ .Values.backstageRoleArn }}"
  CATALOG_REPO_URL: "{{ .Values.secrets.catalogRepoUrl }}"
  TEMPLATES_REPO_URL: "{{ .Values.secrets.templatesRepoUrl }}"
  CATALOG_S3_BUCKET: "{{ .Values.secrets.catalogS3Bucket }}"
  ORGANIZATION_NAME: "{{ .Values.secrets.organizationName }}"
  SCAFFOLDER_DEFAULT_AUTHOR_NAME: "{{ .Values.secrets.scaffolderDefaultAuthorName }}"
  SCAFFOLDER_DEFAULT_AUTHOR_EMAIL: "{{ .Values.secrets.scaffolderDefaultAuthorEmail }}"
  APP_BASE_URL: "{{ .Values.secrets.appBaseUrl }}"
  BACKEND_BASE_URL: "{{ .Values.secrets.backendBaseUrl }}"