# k8s/velero-ui/values.yaml

route:
  enabled: true
  gateway:
    name: tooling-gateway
    namespace: istio-system
    sectionName: https
  hostname: velero-ui.{{ .Values.global.rootDomain }}
  serviceName: velero-ui
  servicePort: 80
