apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.serviceAccount.annotations.eksRoleArn }}
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.annotations.eksRoleArn }}"
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: velero
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: velero
  template:
    metadata:
      labels:
        app: velero
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: velero
          image: velero/velero:v1.17.2
          command:
            - /velero
          args:
            - server
            - --features=
            - --uploader-type=kopia
          env:
            - name: AWS_REGION
              value: {{ .Values.configuration.backupStorageLocation.config.region | quote }}
            - name: BUCKET
              value: {{ .Values.configuration.backupStorageLocation.bucket | quote }}
            - name: VELERO_SCRATCH_DIR
              value: /scratch
          volumeMounts:
            - name: scratch
              mountPath: /scratch
      initContainers: []
      volumes:
        - name: scratch
          emptyDir: {}

