apiVersion: v1
kind: Namespace
metadata:
  name: tooling
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-sa
  namespace: tooling
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.annotations.eksRoleArn | default "" }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: tooling
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: velero
  template:
    metadata:
      labels:
        app: velero
    spec:
      serviceAccountName: velero-sa
      containers:
        - name: velero
          image: velero/velero:v1.12.0
          command:
            - /velero
          args:
            - server
          env:
            - name: AWS_REGION
              value: {{ .Values.configuration.backupStorageLocation.config.region | quote }}
            - name: BUCKET
              value: {{ .Values.configuration.backupStorageLocation.bucket | quote }}
          volumeMounts: []
      initContainers: []
      volumes: []

