# holmes-values.yaml

holmes:
  modelList:
    qwen2.5:
      model: "ollama/qwen2.5:3b"
      type: "ollama"
      base_url: "http://ollama-ollama-server.ai-sre.svc.cluster.local:11434"
      temperature: 0.1
      is_default: true
      max_tokens: 4096
  createServiceAccount: true
  customServiceAccountName: holmes
  customClusterRoleRules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["pods/log"]
      verbs: ["get"]
  env:
    - name: HOLMES_MAX_LOG_LINES
      value: "100"  # Default is often much higher. 150 is enough to see the error.
    - name: HOLMES_MAX_EVENTS
      value: "20"
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
