apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secrets-store-csi-driver-network-policy
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app: secrets-store-csi-driver
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow access from kubelet on nodes
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 9808
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    
    # Allow access to Kubernetes API
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 443
    
    # Allow communication with CSI provider
    - to:
        - podSelector:
            matchLabels:
              app: csi-secrets-store-provider-aws
      ports:
        - protocol: TCP
          port: 8080
