# ==============================================================================
# Velero Backup Configuration
# ==============================================================================

replicaCount: 1

configuration:
  provider: aws
  backupStorageLocation:
    name: default
    bucket: ""
    config:
      region: ""
      s3ForcePathStyle: true
      s3Url: ""
  volumeSnapshotLocation:
    name: default
    config:
      region: ""

serviceAccount:
  create: true
  name: "" # From Terraform
  annotations: {}

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.2 # Use compatible version
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

resources: {}

