apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: holmes
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: ai-sre
  source:
    repoURL: https://github.com/GustavoGuima86/terraform-aws-kubernetes
    targetRevision: new-2026-features
    path: k8s/ai-sre/holmes
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-sre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
