apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/GustavoGuima86/terraform-aws-kubernetes
    targetRevision: new-2026-features
    path: k8s/karpenter
    helm:
      values: |
        karpenter:
          settings:
            awsRegion: "{{ .Values.awsRegion }}"
            clusterName: "{{ .Values.eksClusterName }}"
            clusterEndpoint: "{{ .Values.eksClusterEndpoint }}"
            interruptionQueue: "{{ .Values.karpenterInterruptionQueueName }}"
          defaultNodeRole: "{{ .Values.karpenterNodeIamRoleName }}"
        podAnnotations:
          eks.amazonaws.com/aws-sqs-queue-name: "{{ .Values.karpenterInterruptionQueueName }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
