apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: observability
  source:
    repoURL: https://github.com/GustavoGuima86/terraform-aws-kubernetes
    targetRevision: new-2026-features
    path: k8s/observability/prometheus
    helm:
      valueFiles:
        - values.yaml
      parameters:
      - name: kube-prometheus-stack.grafana.adminPassword
        value: "{{ .Values.grafanaAdminPassword }}"
      - name: kube-prometheus-stack.grafana.additionalDataSources[0].url
        value: "http://loki-gateway.observability.svc:80"
      - name: kube-prometheus-stack.grafana.additionalDataSources[1].url
        value: "http://mimir-mimir-distributed-query-frontend.observability.svc:8080/prometheus"
      - name: kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].url
        value: "http://mimir-mimir-distributed-distributor.observability.svc:8080/api/v1/push"
      - name: kube-prometheus-stack.prometheus.prometheusSpec.externalLabels.cluster
        value: "{{ .Values.eksClusterName }}"
      - name: kube-prometheus-stack.clusterName
        value: "{{ .Values.eksClusterName }}"
      - name: kube-prometheus-stack.awsRegion
        value: "{{ .Values.awsRegion }}"  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
