apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: observability
  source:
    repoURL: https://github.com/GustavoGuima86/terraform-aws-kubernetes
    targetRevision: new-2026-features
    path: k8s/observability/prometheus
    helm:
      valueFiles:
        - values.yaml
      values: |
        kube-prometheus-stack:
          grafana:
            additionalDataSources:
              - name: Loki
                type: loki
                isDefault: false
                editable: true
                access: proxy
                url: "http://loki-gateway.observability.svc:80"
              - name: Mimir
                type: prometheus
                isDefault: false
                editable: true
                access: proxy
                url: "http://mimir-query-frontend.observability.svc:8080/prometheus"
          prometheus:
            prometheusSpec:
              remoteWrite:
                - url: "http://mimir-distributor.observability.svc:8080/api/v1/push"
              externalLabels:
                cluster: "{{ .Values.eksClusterName }}"
          clusterName: "{{ .Values.eksClusterName }}"
          awsRegion: "{{ .Values.awsRegion }}"

        clusterName: "{{ .Values.eksClusterName }}"
        awsRegion: "{{ .Values.awsRegion }}"


  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
