apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: observability
  source:
    repoURL: https://github.com/GustavoGuima86/terraform-aws-kubernetes
    targetRevision: new-2026-features
    path: k8s/observability/loki
    helm:
      valueFiles:
        - values.yaml
      values: |
        loki:
          loki:
            storage_config:
              aws:
                region: "{{ .Values.awsRegion }}"
                bucketnames: "{{ .Values.lokiBucketName }}"
            storage:
              bucketNames:
                chunks: "{{ .Values.lokiBucketName }}"
                ruler: "{{ .Values.lokiBucketName }}"
              s3:
                region: "{{ .Values.awsRegion }}"
          serviceAccount:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: "{{ .Values.lokiServiceAccountRoleArn }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
