apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: observability
  source:
    repoURL: https://github.com/GustavoGuima86/terraform-aws-kubernetes
    targetRevision: new-2026-features
    path: k8s/observability/mimir
    helm:
      valueFiles:
        - values.yaml
      parameters:
      - name: mimir-distributed.mimir.structuredConfig.alertmanager_storage.s3.bucket_name
        value: "{{ .Values.mimirBucketName }}" # Assuming this is the bucket for all. User can specify more if needed.
      - name: mimir-distributed.mimir.structuredConfig.blocks_storage.s3.bucket_name
        value: "{{ .Values.mimirBucketName }}" # Assuming this is the bucket for all. User can specify more if needed.
      - name: mimir-distributed.mimir.structuredConfig.ruler_storage.s3.bucket_name
        value: "{{ .Values.mimirBucketName }}" # Assuming this is the bucket for all. User can specify more if needed.
      - name: mimir-distributed.serviceAccount.name
        value: "{{ .Values.mimirServiceAccountName }}"
      - name: mimir-distributed.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: "{{ .Values.mimirServiceAccountRoleArn }}"
      - name: mimir-distributed.metaMonitoring.serviceMonitor.labels.release
        value: "{{ .Values.kubePrometheusRelease }}"
      - name: mimir-distributed.clusterName
        value: "{{ .Values.eksClusterName }}"
      - name: mimir-distributed.awsRegion
        value: "{{ .Values.awsRegion }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
