apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver-provider-aws
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Deploy after the core CSI driver
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/GustavoGuima86/terraform-aws-kubernetes
    targetRevision: new-2026-features
    path: k8s/secrets-store-csi-driver-provider-aws
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # The provider should be in the same namespace as the core driver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
