apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo.url }}
    targetRevision: {{ .Values.gitRepo.branch }}
    path: k8s/velero
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: configuration.backupStorageLocation.bucket
          value: "{{ .Values.veleroBucketName }}"
        - name: configuration.backupStorageLocation.config.region
          value: "{{ .Values.veleroBucketRegion }}"
        - name: configuration.backupStorageLocation.config.s3Url
          value: "https://s3.{{ .Values.veleroBucketRegion }}.amazonaws.com"
        - name: configuration.volumeSnapshotLocation.config.region
          value: "{{ .Values.veleroBucketRegion }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

