loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: s3
    bucketNames:
      chunks: "" # Set by ArgoCD
      ruler: "" # Set by ArgoCD
    s3:
      region: "" # Set by ArgoCD

  # Use the service account created and associated by Terraform
  serviceAccount:
    create: true
    name: "loki-sa"
    annotations: {}

  # Add placeholders for consistency
  clusterName: "" # Set by ArgoCD
  awsRegion: "" # Set by ArgoCD

# Keep single binary mode
deploymentMode: SingleBinary
singleBinary:
  replicas: 2
# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
