apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - istio-system/main-gateway
{{/*  hosts:*/}}
  - "kagent.{{ .Values.cluster.host }}"
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-ui
        port:
          number: 8080
